### PR TITLE
Add kata

### PR DESCRIPTION
**Pull request by RobA8g**
combined the various edits from before.

signed off: Rob Armstrong <robert.h.armstrong@intel.com>

### CODE REVIEW

**Comment by dankohn** [comment]
Rob, this failed because you used tabs instead of spaces, which you can see in red on the Files Changed tab. https://github.com/lf-edge/lfedge-landscape/pull/81 was working, so I don't know why you closed it. You can just write LGTM if https://deploy-preview-81--lfedge.netlify.com/ looks good and I'll merge it.

**Comment by RobA8g** [comment]
the preview did not build so i attempted to go back and edit.  Also, i consistently get unsuccessful checks for commits to my own repo.  (even though i sign off, same as for the pull request) Any idea why?  

LGTM

**Comment by dankohn** [comment]
The unsuccessful checks are from the DCO which has been disabled for this repot but keeps reappearing for mysterious reasons.

**Comment by dankohn** [comment]
Congrats on your first pull request.

**Pull request merged**
