### PR TITLE
Added Project Eve to the landscape

### PR DESCRIPTION
**Pull request by wesreisz**

### CODE REVIEW

**Comment by wesreisz** [comment]
LGTM

**Comment by dankohn** [comment]
The logo you used has `Engine` in white so it doesn't show. I can ask @alexcontini to change the white text to purple if you want.

**Comment by wesreisz** [comment]
@dankohn Sounds great... can you ask him to just submit a PR with it? There's an issue with the build atm (see failed build above), so it won't be merged right away. I didn't create the original netlify account, so does't look like I can fix it. Reaching out to see if I can find out who owns it.

**Comment by dankohn** [comment]
Alex is a woman. Ibrahim and I have access to the Netlify, but you should be able to see the error that it failed because you removed Kubernetes as graduated. We have a test that looks for it. We'll change the test to look for Eve instead.

**Comment by wesreisz** [comment]
> you should be able to see the error that it failed because you removed Kubernetes as graduated

**Pull request merged**
