### PR TITLE
Adding Open19 Foundation to .ORG category

### PR DESCRIPTION
**Pull request by ninjaginja**
I attempted to convert the logo from png to svg in Illustrator. Let me know if it's not formatted correctly, and I can resolve. Also, I couldn't find an associated crunchbase link.

### CODE REVIEW

**Comment by dankohn** [comment]
Yes, every entry needs a Crunchbase URL. And rather than uploading a logo, you can just set `logo: https://www.opencompute.org/build/assets/media/logo.3658538a.svg`

**Comment by dankohn** [comment]
@ninjaginja Would you like some help fixing this?

**Comment by ninjaginja** [comment]
@dankohn thanks for the assistance. The logo link that you included is for Open Compute Project, not Open19. I think I can get the logo thing figured out, but if there is no Crunchbase link, then do we need to exclude this one from the landscape?

**Comment by dankohn** [comment]
It's free and quick to create an account at Crunchbase and add a new entry for them. Just be sure to include headquarters.

**Comment by dankohn** [comment]
In general, you can't convert from a PNG to an SVG because you're trying to go from low-res to high-res. We can help recreate the PNG as an SVG if you can't get the high-res original in SVG, AI, or EPS formats. What is the Open19 PNG you're trying to use?

**Comment by ninjaginja** [comment]
@dankohn I tried using a method that @wesreisz recommended that involved tracing in Illustrator, but I must have misunderstood that you can't start from png. I've removed both incorrectly formatted svg files (for Open19 and Open Compute Foundation) and attached the png files. I also added a Crunchbase profile for Open19 and added a link in the yml.

open-compute-project_stacked
open19-foundation

**Comment by dankohn** [comment]
My comment was unclear. You definitely can use autotrace in Illustrator, but it only works well on shapes. For fonts, you want to identify and recreate it. @alexcontini could you please create an SVG version of: 

image

For OpenCompute, I suggest using:

`logo: 'https://www.zutacore.com/images/events/open-compute-logo.svg'`

**Comment by dankohn** [comment]
I would recommend that you remove Open19 from this PR as the Open Compute Project entry should be ready to post. Then, you can do Open19 as a separate PR.

**Comment by dankohn** [comment]
[open19.svg.zip](https://github.com/lf-edge/lfedge-landscape/files/3472734/open19.svg.zip)

Here's the Open19 SVG (attached as a ZIP because GitHub doesn't allow attaching SVGs). You should now have what you need to add these two items.

**Comment by dankohn** [comment]
Handled in #68

**Pull request closed without merging**
