### PR TITLE
OpenStack

### PR DESCRIPTION
**Pull request by ninjaginja**
adding OpenStack to org category

### CODE REVIEW

**Comment by dankohn** [comment]
Please do a new branch for each change you're looking at so they can be evaluated separately. Let me know if you need some help.

**Comment by dankohn** [comment]
`3:56:50 PM: Fatal: Open Compute Project Foundation has a twitter https://twitter.com/Opencomputeprj/ which ends with /`

I'm fixing

**Comment by ninjaginja** [comment]
Sorry for the all the confusion @dankohn. I was trying to create separate branches for the 2 new PRs (CNCF, OpenStack). I don't know how/why all those previous commits are showing up here.

**Comment by dankohn** [comment]
If you open a free Slack account at slack.cncf.io I'm happy to help one on one. But, basically, each time you make a change, you want to start by editing https://github.com/lf-edge/lfedge-landscape/blob/master/landscape.yml and not your existing fork. When you have a chance to save changes, you need to do it in a new branch each time.

**Comment by dankohn** [comment]
But, this now looks OK, so congratulations. I'll close the other two PRs which duplicate this one.

**Comment by wesreisz** [comment]
Merging this one... lgtm

**Pull request merged**
