### PR TITLE
Update landscape.yml

### PR DESCRIPTION
**Pull request by RobA8g**
Add Kata containers

Signed off: Rob Armstrong <robert.h.armstrong@intel.com>

### CODE REVIEW

**Comment by RobA8g** [comment]
Added Kata with revised crunchbase address

Signed off: Rob Armstrong <robert.h.armstrong@intel.com>

**Comment by dankohn** [comment]
Getting close now. You need to set the GitHub repo to `https://github.com/kata-containers/runtime`.

**Comment by RobA8g** [comment]
updated kata Git to: https://github.com/kata-containers/runtime

Signed off: Rob Armstrong <robert.h.armstrong@intel.com>

**Comment by dankohn** [comment]
Now, just write LGTM if the preview at https://deploy-preview-81--lfedge.netlify.com looks good.

**Comment by RobA8g** [comment]
git rebase HEAD~7 --Signed off: Rob Armstrong robert.h.armstrong@intel.com

**Comment by RobA8g** [comment]
git push --force-with-lease origin master

**Pull request closed without merging**
